"""create safety valve and work order table

Revision ID: 598dcb8a58f4
Revises: f90149ee77ae
Create Date: 2025-09-21 23:23:47.577327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '598dcb8a58f4'
down_revision: Union[str, Sequence[str], None] = 'f90149ee77ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('safety_valve',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('description', sa.String(length=100), nullable=False),
    sa.Column('tag', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=100), nullable=False),
    sa.Column('serial_number', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('size', sa.String(length=20), nullable=False),
    sa.Column('actuation_range', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('work_order',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('work_order_number', sa.String(length=20), nullable=True),
    sa.Column('calibration_date', sa.Date(), nullable=True),
    sa.Column('validate_date', sa.Date(), nullable=True),
    sa.Column('issue_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid'),
    sa.UniqueConstraint('work_order_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_order')
    op.drop_table('safety_valve')
    # ### end Alembic commands ###
