"""create customers table

Revision ID: f90149ee77ae
Revises: 
Create Date: 2025-09-21 23:06:47.074928

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f90149ee77ae'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('fantasy_name', sa.String(), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('cnpj_formated', sa.String(length=18), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_customers_cnpj'), 'customers', ['cnpj'], unique=False)
    op.create_index(op.f('ix_customers_cnpj_formated'), 'customers', ['cnpj_formated'], unique=False)
    op.create_index(op.f('ix_customers_fantasy_name'), 'customers', ['fantasy_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customers_fantasy_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_cnpj_formated'), table_name='customers')
    op.drop_index(op.f('ix_customers_cnpj'), table_name='customers')
    op.drop_table('customers')
    # ### end Alembic commands ###
